server:
  address: :8080
database:
  driver: mysql
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  dbname: ttds

redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0

jwt:
  secret: ttds
  expires: 240h
  refresh_secret: ttds_refresh
  refresh_expires: 720h