env: dev # dev, prod

server:
  address: :8080
db:
  driver: mysql
  username: root
  password: 123456
  host: 127.0.0.1
  port: 3306
  dbname: ttds

redis:
  host: 127.0.0.1
  port: 6379
  password:
  db: 0

oss:
  endpoint: http://127.0.0.1:9000
  access_key_id:
  secret_access_key:
  bucket_name: ttds-bucket

jwt:
  secret: ttds
  refresh_secret: ttds-refresh
  expires: 240h
  refresh_expires: 240h

log:
  level: info
  path: ./logs
  filename: ttds.log